### ISSUE TITLE
A consultation regarding the chamfer distance.

### ISSUE THREAD

**Issue by yhbian** [KuofengGao/IRBA#1]
Thank you very much for sharing the code of this wonderful work, which has brought me great convenience and inspiration! 

I have a slight problem with TABLE VIII. I adopt the WLT of default settings and evaluate the average **Chamfer(pc_normalize(x), pc_normalize(WLT(x)))** on all three test sets respectively. Both PointBA and WLT achieve much higher chamfer distances than in TABLE VIII. 

I wonder whether the difference comes from calculating details(like normalization or not) since the absolute scale can significantly affect the chamfer distance.

**Comment by KuofengGao** [comment]
Hi, thanks for your attention for our work!

We have uploaded the code about the calculation of Chamfer Distance.

Hope that it could be of benefit to you in your work.

**Comment by yhbian** [comment]
It is indeed due to the scale. I add **pc = pc * 0.5 + 0.5** in my code and our results are aligned. Thank you for your response! (^o^)
